/* tslint:disable */
/* eslint-disable */
/**
 * Org Note API
 * List of methods for work with Org Note.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: artawower@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * File change information for synchronization
 * @export
 * @interface FileChange
 */
export interface FileChange {
    /**
     * 
     * @type {string}
     * @memberof FileChange
     */
    'contentHash'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof FileChange
     */
    'deleted': boolean;
    /**
     * 
     * @type {string}
     * @memberof FileChange
     */
    'deletedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof FileChange
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof FileChange
     */
    'path': string;
    /**
     * 
     * @type {number}
     * @memberof FileChange
     */
    'size'?: number;
    /**
     * 
     * @type {string}
     * @memberof FileChange
     */
    'updatedAt': string;
    /**
     * 
     * @type {number}
     * @memberof FileChange
     */
    'version': number;
}
/**
 * Response after successful file upload
 * @export
 * @interface FileUploadResponse
 */
export interface FileUploadResponse {
    /**
     * 
     * @type {string}
     * @memberof FileUploadResponse
     */
    'contentHash': string;
    /**
     * 
     * @type {string}
     * @memberof FileUploadResponse
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof FileUploadResponse
     */
    'path': string;
    /**
     * 
     * @type {number}
     * @memberof FileUploadResponse
     */
    'size': number;
    /**
     * 
     * @type {string}
     * @memberof FileUploadResponse
     */
    'updatedAt': string;
    /**
     * 
     * @type {boolean}
     * @memberof FileUploadResponse
     */
    'uploaded': boolean;
    /**
     * 
     * @type {number}
     * @memberof FileUploadResponse
     */
    'version': number;
}
/**
 * 
 * @export
 * @interface HandlersHttpErrorAny
 */
export interface HandlersHttpErrorAny {
    /**
     * 
     * @type {object}
     * @memberof HandlersHttpErrorAny
     */
    'data'?: object;
    /**
     * 
     * @type {string}
     * @memberof HandlersHttpErrorAny
     */
    'message'?: string;
}
/**
 * 
 * @export
 * @interface HandlersHttpResponseArrayModelsAPITokenAny
 */
export interface HandlersHttpResponseArrayModelsAPITokenAny {
    /**
     * 
     * @type {Array<ModelsAPIToken>}
     * @memberof HandlersHttpResponseArrayModelsAPITokenAny
     */
    'data'?: Array<ModelsAPIToken>;
    /**
     * 
     * @type {object}
     * @memberof HandlersHttpResponseArrayModelsAPITokenAny
     */
    'meta'?: object;
}
/**
 * 
 * @export
 * @interface HandlersHttpResponseFileUploadResponseAny
 */
export interface HandlersHttpResponseFileUploadResponseAny {
    /**
     * 
     * @type {FileUploadResponse}
     * @memberof HandlersHttpResponseFileUploadResponseAny
     */
    'data'?: FileUploadResponse;
    /**
     * 
     * @type {object}
     * @memberof HandlersHttpResponseFileUploadResponseAny
     */
    'meta'?: object;
}
/**
 * 
 * @export
 * @interface HandlersHttpResponseHandlersOAuthRedirectDataAny
 */
export interface HandlersHttpResponseHandlersOAuthRedirectDataAny {
    /**
     * 
     * @type {HandlersOAuthRedirectData}
     * @memberof HandlersHttpResponseHandlersOAuthRedirectDataAny
     */
    'data'?: HandlersOAuthRedirectData;
    /**
     * 
     * @type {object}
     * @memberof HandlersHttpResponseHandlersOAuthRedirectDataAny
     */
    'meta'?: object;
}
/**
 * 
 * @export
 * @interface HandlersHttpResponseModelsAPITokenAny
 */
export interface HandlersHttpResponseModelsAPITokenAny {
    /**
     * 
     * @type {ModelsAPIToken}
     * @memberof HandlersHttpResponseModelsAPITokenAny
     */
    'data'?: ModelsAPIToken;
    /**
     * 
     * @type {object}
     * @memberof HandlersHttpResponseModelsAPITokenAny
     */
    'meta'?: object;
}
/**
 * 
 * @export
 * @interface HandlersHttpResponseModelsFileMetadataAny
 */
export interface HandlersHttpResponseModelsFileMetadataAny {
    /**
     * 
     * @type {ModelsFileMetadata}
     * @memberof HandlersHttpResponseModelsFileMetadataAny
     */
    'data'?: ModelsFileMetadata;
    /**
     * 
     * @type {object}
     * @memberof HandlersHttpResponseModelsFileMetadataAny
     */
    'meta'?: object;
}
/**
 * 
 * @export
 * @interface HandlersHttpResponseModelsUserPersonalInfoAny
 */
export interface HandlersHttpResponseModelsUserPersonalInfoAny {
    /**
     * 
     * @type {ModelsUserPersonalInfo}
     * @memberof HandlersHttpResponseModelsUserPersonalInfoAny
     */
    'data'?: ModelsUserPersonalInfo;
    /**
     * 
     * @type {object}
     * @memberof HandlersHttpResponseModelsUserPersonalInfoAny
     */
    'meta'?: object;
}
/**
 * 
 * @export
 * @interface HandlersHttpResponseSyncChangesResponseAny
 */
export interface HandlersHttpResponseSyncChangesResponseAny {
    /**
     * 
     * @type {SyncChangesResponse}
     * @memberof HandlersHttpResponseSyncChangesResponseAny
     */
    'data'?: SyncChangesResponse;
    /**
     * 
     * @type {object}
     * @memberof HandlersHttpResponseSyncChangesResponseAny
     */
    'meta'?: object;
}
/**
 * 
 * @export
 * @interface HandlersOAuthRedirectData
 */
export interface HandlersOAuthRedirectData {
    /**
     * 
     * @type {string}
     * @memberof HandlersOAuthRedirectData
     */
    'redirectUrl'?: string;
}
/**
 * 
 * @export
 * @interface HandlersSubscribeBody
 */
export interface HandlersSubscribeBody {
    /**
     * 
     * @type {string}
     * @memberof HandlersSubscribeBody
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof HandlersSubscribeBody
     */
    'token'?: string;
}
/**
 * 
 * @export
 * @interface HandlersSystemInfo
 */
export interface HandlersSystemInfo {
    /**
     * 
     * @type {ModelsEnvironmentInfo}
     * @memberof HandlersSystemInfo
     */
    'environment'?: ModelsEnvironmentInfo;
    /**
     * 
     * @type {ModelsOrgNoteClientUpdateInfo}
     * @memberof HandlersSystemInfo
     */
    'update'?: ModelsOrgNoteClientUpdateInfo;
}
/**
 * 
 * @export
 * @interface ModelsAPIToken
 */
export interface ModelsAPIToken {
    /**
     * 
     * @type {string}
     * @memberof ModelsAPIToken
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsAPIToken
     */
    'permission'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsAPIToken
     */
    'token'?: string;
}
/**
 * 
 * @export
 * @interface ModelsEnvironmentInfo
 */
export interface ModelsEnvironmentInfo {
    /**
     * 
     * @type {boolean}
     * @memberof ModelsEnvironmentInfo
     */
    'selfHosted'?: boolean;
}
/**
 * 
 * @export
 * @interface ModelsFileMetadata
 */
export interface ModelsFileMetadata {
    /**
     * 
     * @type {string}
     * @memberof ModelsFileMetadata
     */
    'contentHash'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsFileMetadata
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsFileMetadata
     */
    'deletedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsFileMetadata
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsFileMetadata
     */
    'path'?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsFileMetadata
     */
    'size'?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsFileMetadata
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsFileMetadata
     */
    'userId'?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsFileMetadata
     */
    'version'?: number;
}
/**
 * 
 * @export
 * @interface ModelsOrgNoteClientUpdateInfo
 */
export interface ModelsOrgNoteClientUpdateInfo {
    /**
     * 
     * @type {string}
     * @memberof ModelsOrgNoteClientUpdateInfo
     */
    'changeLog'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsOrgNoteClientUpdateInfo
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsOrgNoteClientUpdateInfo
     */
    'version'?: string;
}
/**
 * 
 * @export
 * @interface ModelsUserPersonalInfo
 */
export interface ModelsUserPersonalInfo {
    /**
     * 
     * @type {string}
     * @memberof ModelsUserPersonalInfo
     */
    'active'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUserPersonalInfo
     */
    'avatarUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUserPersonalInfo
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUserPersonalInfo
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUserPersonalInfo
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUserPersonalInfo
     */
    'nickName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUserPersonalInfo
     */
    'profileUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUserPersonalInfo
     */
    'provider'?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsUserPersonalInfo
     */
    'spaceLimit'?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsUserPersonalInfo
     */
    'usedSpace'?: number;
}
/**
 * Response containing file changes since last sync
 * @export
 * @interface SyncChangesResponse
 */
export interface SyncChangesResponse {
    /**
     * 
     * @type {Array<FileChange>}
     * @memberof SyncChangesResponse
     */
    'changes': Array<FileChange>;
    /**
     * 
     * @type {string}
     * @memberof SyncChangesResponse
     */
    'cursor'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SyncChangesResponse
     */
    'hasMore': boolean;
    /**
     * 
     * @type {string}
     * @memberof SyncChangesResponse
     */
    'serverTime': string;
}
/**
 * Response when optimistic locking fails due to version mismatch
 * @export
 * @interface VersionConflictResponse
 */
export interface VersionConflictResponse {
    /**
     * 
     * @type {string}
     * @memberof VersionConflictResponse
     */
    'error': string;
    /**
     * 
     * @type {string}
     * @memberof VersionConflictResponse
     */
    'path': string;
    /**
     * 
     * @type {number}
     * @memberof VersionConflictResponse
     */
    'serverVersion': number;
}

/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Delete user account
         * @summary Delete user account
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authAccountDelete: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/account`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Return all available API tokens
         * @summary Get API tokens
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authApiTokensGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/api-tokens`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLogoutGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Callback for OAuth
         * @param {string} provider provider
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authProviderCallbackGet: async (provider: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'provider' is not null or undefined
            assertParamExists('authProviderCallbackGet', 'provider', provider)
            const localVarPath = `/auth/{provider}/callback`
                .replace(`{${"provider"}}`, encodeURIComponent(String(provider)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Entrypoint for login
         * @summary OAuth Login
         * @param {string} provider provider
         * @param {string} [state] OAuth state
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authProviderLoginGet: async (provider: string, state?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'provider' is not null or undefined
            assertParamExists('authProviderLoginGet', 'provider', provider)
            const localVarPath = `/auth/{provider}/login`
                .replace(`{${"provider"}}`, encodeURIComponent(String(provider)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (state !== undefined) {
                localVarQueryParameter['state'] = state;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Subscribe for backend features, like sync notes
         * @summary Subscribe
         * @param {HandlersSubscribeBody} data token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authSubscribePost: async (data: HandlersSubscribeBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'data' is not null or undefined
            assertParamExists('authSubscribePost', 'data', data)
            const localVarPath = `/auth/subscribe`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(data, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create API token
         * @summary Create API token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authTokenPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/token`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete API token
         * @summary Delete API token
         * @param {string} tokenId token id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authTokenTokenIdDelete: async (tokenId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tokenId' is not null or undefined
            assertParamExists('authTokenTokenIdDelete', 'tokenId', tokenId)
            const localVarPath = `/auth/token/{tokenId}`
                .replace(`{${"tokenId"}}`, encodeURIComponent(String(tokenId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Return found user by provided token
         * @summary Verify user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authVerifyGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/verify`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * Delete user account
         * @summary Delete user account
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authAccountDelete(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authAccountDelete(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authAccountDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Return all available API tokens
         * @summary Get API tokens
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authApiTokensGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HandlersHttpResponseArrayModelsAPITokenAny>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authApiTokensGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authApiTokensGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authLogoutGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authLogoutGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authLogoutGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Callback for OAuth
         * @param {string} provider provider
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authProviderCallbackGet(provider: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authProviderCallbackGet(provider, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authProviderCallbackGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Entrypoint for login
         * @summary OAuth Login
         * @param {string} provider provider
         * @param {string} [state] OAuth state
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authProviderLoginGet(provider: string, state?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HandlersHttpResponseHandlersOAuthRedirectDataAny>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authProviderLoginGet(provider, state, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authProviderLoginGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Subscribe for backend features, like sync notes
         * @summary Subscribe
         * @param {HandlersSubscribeBody} data token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authSubscribePost(data: HandlersSubscribeBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authSubscribePost(data, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authSubscribePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Create API token
         * @summary Create API token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authTokenPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HandlersHttpResponseModelsAPITokenAny>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authTokenPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authTokenPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Delete API token
         * @summary Delete API token
         * @param {string} tokenId token id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authTokenTokenIdDelete(tokenId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authTokenTokenIdDelete(tokenId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authTokenTokenIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Return found user by provided token
         * @summary Verify user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authVerifyGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HandlersHttpResponseModelsUserPersonalInfoAny>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authVerifyGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authVerifyGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * Delete user account
         * @summary Delete user account
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authAccountDelete(options?: any): AxiosPromise<object> {
            return localVarFp.authAccountDelete(options).then((request) => request(axios, basePath));
        },
        /**
         * Return all available API tokens
         * @summary Get API tokens
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authApiTokensGet(options?: any): AxiosPromise<HandlersHttpResponseArrayModelsAPITokenAny> {
            return localVarFp.authApiTokensGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLogoutGet(options?: any): AxiosPromise<object> {
            return localVarFp.authLogoutGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Callback for OAuth
         * @param {string} provider provider
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authProviderCallbackGet(provider: string, options?: any): AxiosPromise<object> {
            return localVarFp.authProviderCallbackGet(provider, options).then((request) => request(axios, basePath));
        },
        /**
         * Entrypoint for login
         * @summary OAuth Login
         * @param {string} provider provider
         * @param {string} [state] OAuth state
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authProviderLoginGet(provider: string, state?: string, options?: any): AxiosPromise<HandlersHttpResponseHandlersOAuthRedirectDataAny> {
            return localVarFp.authProviderLoginGet(provider, state, options).then((request) => request(axios, basePath));
        },
        /**
         * Subscribe for backend features, like sync notes
         * @summary Subscribe
         * @param {HandlersSubscribeBody} data token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authSubscribePost(data: HandlersSubscribeBody, options?: any): AxiosPromise<object> {
            return localVarFp.authSubscribePost(data, options).then((request) => request(axios, basePath));
        },
        /**
         * Create API token
         * @summary Create API token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authTokenPost(options?: any): AxiosPromise<HandlersHttpResponseModelsAPITokenAny> {
            return localVarFp.authTokenPost(options).then((request) => request(axios, basePath));
        },
        /**
         * Delete API token
         * @summary Delete API token
         * @param {string} tokenId token id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authTokenTokenIdDelete(tokenId: string, options?: any): AxiosPromise<object> {
            return localVarFp.authTokenTokenIdDelete(tokenId, options).then((request) => request(axios, basePath));
        },
        /**
         * Return found user by provided token
         * @summary Verify user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authVerifyGet(options?: any): AxiosPromise<HandlersHttpResponseModelsUserPersonalInfoAny> {
            return localVarFp.authVerifyGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI {
    /**
     * Delete user account
     * @summary Delete user account
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authAccountDelete(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authAccountDelete(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Return all available API tokens
     * @summary Get API tokens
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authApiTokensGet(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authApiTokensGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Logout
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authLogoutGet(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authLogoutGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Callback for OAuth
     * @param {string} provider provider
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authProviderCallbackGet(provider: string, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authProviderCallbackGet(provider, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Entrypoint for login
     * @summary OAuth Login
     * @param {string} provider provider
     * @param {string} [state] OAuth state
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authProviderLoginGet(provider: string, state?: string, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authProviderLoginGet(provider, state, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Subscribe for backend features, like sync notes
     * @summary Subscribe
     * @param {HandlersSubscribeBody} data token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authSubscribePost(data: HandlersSubscribeBody, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authSubscribePost(data, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create API token
     * @summary Create API token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authTokenPost(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authTokenPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete API token
     * @summary Delete API token
     * @param {string} tokenId token id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authTokenTokenIdDelete(tokenId: string, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authTokenTokenIdDelete(tokenId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Return found user by provided token
     * @summary Verify user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authVerifyGet(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authVerifyGet(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * EventsApi - axios parameter creator
 * @export
 */
export const EventsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Generic WebSocket endpoint for real-time user events (sync, notifications, etc). Requires `Upgrade: websocket` header.
         * @summary WebSocket Events Channel
         * @param {string} [token] Auth token (alternative to Authorization header)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wsEventsGet: async (token?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/ws/events`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (token !== undefined) {
                localVarQueryParameter['token'] = token;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EventsApi - functional programming interface
 * @export
 */
export const EventsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EventsApiAxiosParamCreator(configuration)
    return {
        /**
         * Generic WebSocket endpoint for real-time user events (sync, notifications, etc). Requires `Upgrade: websocket` header.
         * @summary WebSocket Events Channel
         * @param {string} [token] Auth token (alternative to Authorization header)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wsEventsGet(token?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.wsEventsGet(token, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventsApi.wsEventsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * EventsApi - factory interface
 * @export
 */
export const EventsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EventsApiFp(configuration)
    return {
        /**
         * Generic WebSocket endpoint for real-time user events (sync, notifications, etc). Requires `Upgrade: websocket` header.
         * @summary WebSocket Events Channel
         * @param {string} [token] Auth token (alternative to Authorization header)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wsEventsGet(token?: string, options?: any): AxiosPromise<void> {
            return localVarFp.wsEventsGet(token, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * EventsApi - object-oriented interface
 * @export
 * @class EventsApi
 * @extends {BaseAPI}
 */
export class EventsApi extends BaseAPI {
    /**
     * Generic WebSocket endpoint for real-time user events (sync, notifications, etc). Requires `Upgrade: websocket` header.
     * @summary WebSocket Events Channel
     * @param {string} [token] Auth token (alternative to Authorization header)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsApi
     */
    public wsEventsGet(token?: string, options?: RawAxiosRequestConfig) {
        return EventsApiFp(this.configuration).wsEventsGet(token, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * SyncApi - axios parameter creator
 * @export
 */
export const SyncApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns file changes since the specified timestamp
         * @summary Get file changes
         * @param {number} [since] Unix timestamp in milliseconds for incremental sync
         * @param {number} [limit] Maximum number of changes to return (default: 100, max: 500)
         * @param {string} [cursor] Pagination cursor
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        syncChangesGet: async (since?: number, limit?: number, cursor?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/sync/changes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (since !== undefined) {
                localVarQueryParameter['since'] = since;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Soft delete a file (creates tombstone for sync)
         * @summary Delete a file
         * @param {string} path File path
         * @param {number} [version] Expected version for optimistic locking
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        syncFilesDelete: async (path: string, version?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'path' is not null or undefined
            assertParamExists('syncFilesDelete', 'path', path)
            const localVarPath = `/sync/files`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (path !== undefined) {
                localVarQueryParameter['path'] = path;
            }

            if (version !== undefined) {
                localVarQueryParameter['version'] = version;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Download file content by path
         * @summary Download a file
         * @param {string} path File path
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        syncFilesGet: async (path: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'path' is not null or undefined
            assertParamExists('syncFilesGet', 'path', path)
            const localVarPath = `/sync/files`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (path !== undefined) {
                localVarQueryParameter['path'] = path;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Upload a file to sync storage with content-addressable deduplication
         * @summary Upload a file
         * @param {string} filePath Relative file path
         * @param {File} file File content
         * @param {string} [xContentHash] SHA-256 hash for verification
         * @param {number} [expectedVersion] Expected version for optimistic locking
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        syncFilesPut: async (filePath: string, file: File, xContentHash?: string, expectedVersion?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'filePath' is not null or undefined
            assertParamExists('syncFilesPut', 'filePath', filePath)
            // verify required parameter 'file' is not null or undefined
            assertParamExists('syncFilesPut', 'file', file)
            const localVarPath = `/sync/files`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            if (xContentHash != null) {
                localVarHeaderParameter['X-Content-Hash'] = String(xContentHash);
            }


            if (filePath !== undefined) { 
                localVarFormParams.append('filePath', filePath as any);
            }
    
            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
    
            if (expectedVersion !== undefined) { 
                localVarFormParams.append('expectedVersion', expectedVersion as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SyncApi - functional programming interface
 * @export
 */
export const SyncApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SyncApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns file changes since the specified timestamp
         * @summary Get file changes
         * @param {number} [since] Unix timestamp in milliseconds for incremental sync
         * @param {number} [limit] Maximum number of changes to return (default: 100, max: 500)
         * @param {string} [cursor] Pagination cursor
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async syncChangesGet(since?: number, limit?: number, cursor?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HandlersHttpResponseSyncChangesResponseAny>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.syncChangesGet(since, limit, cursor, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SyncApi.syncChangesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Soft delete a file (creates tombstone for sync)
         * @summary Delete a file
         * @param {string} path File path
         * @param {number} [version] Expected version for optimistic locking
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async syncFilesDelete(path: string, version?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HandlersHttpResponseModelsFileMetadataAny>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.syncFilesDelete(path, version, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SyncApi.syncFilesDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Download file content by path
         * @summary Download a file
         * @param {string} path File path
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async syncFilesGet(path: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.syncFilesGet(path, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SyncApi.syncFilesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Upload a file to sync storage with content-addressable deduplication
         * @summary Upload a file
         * @param {string} filePath Relative file path
         * @param {File} file File content
         * @param {string} [xContentHash] SHA-256 hash for verification
         * @param {number} [expectedVersion] Expected version for optimistic locking
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async syncFilesPut(filePath: string, file: File, xContentHash?: string, expectedVersion?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HandlersHttpResponseFileUploadResponseAny>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.syncFilesPut(filePath, file, xContentHash, expectedVersion, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SyncApi.syncFilesPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SyncApi - factory interface
 * @export
 */
export const SyncApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SyncApiFp(configuration)
    return {
        /**
         * Returns file changes since the specified timestamp
         * @summary Get file changes
         * @param {number} [since] Unix timestamp in milliseconds for incremental sync
         * @param {number} [limit] Maximum number of changes to return (default: 100, max: 500)
         * @param {string} [cursor] Pagination cursor
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        syncChangesGet(since?: number, limit?: number, cursor?: string, options?: any): AxiosPromise<HandlersHttpResponseSyncChangesResponseAny> {
            return localVarFp.syncChangesGet(since, limit, cursor, options).then((request) => request(axios, basePath));
        },
        /**
         * Soft delete a file (creates tombstone for sync)
         * @summary Delete a file
         * @param {string} path File path
         * @param {number} [version] Expected version for optimistic locking
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        syncFilesDelete(path: string, version?: number, options?: any): AxiosPromise<HandlersHttpResponseModelsFileMetadataAny> {
            return localVarFp.syncFilesDelete(path, version, options).then((request) => request(axios, basePath));
        },
        /**
         * Download file content by path
         * @summary Download a file
         * @param {string} path File path
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        syncFilesGet(path: string, options?: any): AxiosPromise<File> {
            return localVarFp.syncFilesGet(path, options).then((request) => request(axios, basePath));
        },
        /**
         * Upload a file to sync storage with content-addressable deduplication
         * @summary Upload a file
         * @param {string} filePath Relative file path
         * @param {File} file File content
         * @param {string} [xContentHash] SHA-256 hash for verification
         * @param {number} [expectedVersion] Expected version for optimistic locking
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        syncFilesPut(filePath: string, file: File, xContentHash?: string, expectedVersion?: number, options?: any): AxiosPromise<HandlersHttpResponseFileUploadResponseAny> {
            return localVarFp.syncFilesPut(filePath, file, xContentHash, expectedVersion, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SyncApi - object-oriented interface
 * @export
 * @class SyncApi
 * @extends {BaseAPI}
 */
export class SyncApi extends BaseAPI {
    /**
     * Returns file changes since the specified timestamp
     * @summary Get file changes
     * @param {number} [since] Unix timestamp in milliseconds for incremental sync
     * @param {number} [limit] Maximum number of changes to return (default: 100, max: 500)
     * @param {string} [cursor] Pagination cursor
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SyncApi
     */
    public syncChangesGet(since?: number, limit?: number, cursor?: string, options?: RawAxiosRequestConfig) {
        return SyncApiFp(this.configuration).syncChangesGet(since, limit, cursor, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Soft delete a file (creates tombstone for sync)
     * @summary Delete a file
     * @param {string} path File path
     * @param {number} [version] Expected version for optimistic locking
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SyncApi
     */
    public syncFilesDelete(path: string, version?: number, options?: RawAxiosRequestConfig) {
        return SyncApiFp(this.configuration).syncFilesDelete(path, version, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Download file content by path
     * @summary Download a file
     * @param {string} path File path
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SyncApi
     */
    public syncFilesGet(path: string, options?: RawAxiosRequestConfig) {
        return SyncApiFp(this.configuration).syncFilesGet(path, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Upload a file to sync storage with content-addressable deduplication
     * @summary Upload a file
     * @param {string} filePath Relative file path
     * @param {File} file File content
     * @param {string} [xContentHash] SHA-256 hash for verification
     * @param {number} [expectedVersion] Expected version for optimistic locking
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SyncApi
     */
    public syncFilesPut(filePath: string, file: File, xContentHash?: string, expectedVersion?: number, options?: RawAxiosRequestConfig) {
        return SyncApiFp(this.configuration).syncFilesPut(filePath, file, xContentHash, expectedVersion, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * SystemInfoApi - axios parameter creator
 * @export
 */
export const SystemInfoApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary GetLatestClientUpdate
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        systemInfoClientUpdateLatestGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/system-info/client-update/latest`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary GetUpdatesFromVersion
         * @param {string} version provider
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        systemInfoClientUpdateVersionGet: async (version: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'version' is not null or undefined
            assertParamExists('systemInfoClientUpdateVersionGet', 'version', version)
            const localVarPath = `/system-info/client-update/{version}`
                .replace(`{${"version"}}`, encodeURIComponent(String(version)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get system info
         * @summary GetSystemInfo
         * @param {string} version provider
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        systemInfoVersionGet: async (version: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'version' is not null or undefined
            assertParamExists('systemInfoVersionGet', 'version', version)
            const localVarPath = `/system-info/{version}`
                .replace(`{${"version"}}`, encodeURIComponent(String(version)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SystemInfoApi - functional programming interface
 * @export
 */
export const SystemInfoApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SystemInfoApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary GetLatestClientUpdate
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async systemInfoClientUpdateLatestGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ModelsOrgNoteClientUpdateInfo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.systemInfoClientUpdateLatestGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SystemInfoApi.systemInfoClientUpdateLatestGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary GetUpdatesFromVersion
         * @param {string} version provider
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async systemInfoClientUpdateVersionGet(version: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ModelsOrgNoteClientUpdateInfo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.systemInfoClientUpdateVersionGet(version, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SystemInfoApi.systemInfoClientUpdateVersionGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get system info
         * @summary GetSystemInfo
         * @param {string} version provider
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async systemInfoVersionGet(version: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HandlersSystemInfo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.systemInfoVersionGet(version, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SystemInfoApi.systemInfoVersionGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SystemInfoApi - factory interface
 * @export
 */
export const SystemInfoApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SystemInfoApiFp(configuration)
    return {
        /**
         * 
         * @summary GetLatestClientUpdate
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        systemInfoClientUpdateLatestGet(options?: any): AxiosPromise<ModelsOrgNoteClientUpdateInfo> {
            return localVarFp.systemInfoClientUpdateLatestGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary GetUpdatesFromVersion
         * @param {string} version provider
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        systemInfoClientUpdateVersionGet(version: string, options?: any): AxiosPromise<ModelsOrgNoteClientUpdateInfo> {
            return localVarFp.systemInfoClientUpdateVersionGet(version, options).then((request) => request(axios, basePath));
        },
        /**
         * Get system info
         * @summary GetSystemInfo
         * @param {string} version provider
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        systemInfoVersionGet(version: string, options?: any): AxiosPromise<HandlersSystemInfo> {
            return localVarFp.systemInfoVersionGet(version, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SystemInfoApi - object-oriented interface
 * @export
 * @class SystemInfoApi
 * @extends {BaseAPI}
 */
export class SystemInfoApi extends BaseAPI {
    /**
     * 
     * @summary GetLatestClientUpdate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SystemInfoApi
     */
    public systemInfoClientUpdateLatestGet(options?: RawAxiosRequestConfig) {
        return SystemInfoApiFp(this.configuration).systemInfoClientUpdateLatestGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary GetUpdatesFromVersion
     * @param {string} version provider
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SystemInfoApi
     */
    public systemInfoClientUpdateVersionGet(version: string, options?: RawAxiosRequestConfig) {
        return SystemInfoApiFp(this.configuration).systemInfoClientUpdateVersionGet(version, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get system info
     * @summary GetSystemInfo
     * @param {string} version provider
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SystemInfoApi
     */
    public systemInfoVersionGet(version: string, options?: RawAxiosRequestConfig) {
        return SystemInfoApiFp(this.configuration).systemInfoVersionGet(version, options).then((request) => request(this.axios, this.basePath));
    }
}



