/* tslint:disable */
/* eslint-disable */
/**
 * Org Note API
 * List of methods for work with Org Note.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: artawower@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface FilesUploadPostRequest
 */
export interface FilesUploadPostRequest {
    /**
     * files
     * @type {Array<string>}
     * @memberof FilesUploadPostRequest
     */
    'files': Array<string>;
}
/**
 * 
 * @export
 * @interface HandlersCreatingNote
 */
export interface HandlersCreatingNote {
    /**
     * 
     * @type {string}
     * @memberof HandlersCreatingNote
     */
    'content': string;
    /**
     * 
     * @type {string}
     * @memberof HandlersCreatingNote
     */
    'createdAt'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof HandlersCreatingNote
     */
    'encrypted'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof HandlersCreatingNote
     */
    'encryptionType'?: HandlersCreatingNoteEncryptionTypeEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof HandlersCreatingNote
     */
    'filePath'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof HandlersCreatingNote
     */
    'id'?: string;
    /**
     * 
     * @type {ModelsNoteMeta}
     * @memberof HandlersCreatingNote
     */
    'meta'?: ModelsNoteMeta;
    /**
     * 
     * @type {string}
     * @memberof HandlersCreatingNote
     */
    'touchedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof HandlersCreatingNote
     */
    'updatedAt'?: string;
}

export const HandlersCreatingNoteEncryptionTypeEnum = {
    GpgKeys: 'gpgKeys',
    GpgPassword: 'gpgPassword',
    Disabled: 'disabled'
} as const;

export type HandlersCreatingNoteEncryptionTypeEnum = typeof HandlersCreatingNoteEncryptionTypeEnum[keyof typeof HandlersCreatingNoteEncryptionTypeEnum];

/**
 * 
 * @export
 * @interface HandlersDeletedNote
 */
export interface HandlersDeletedNote {
    /**
     * 
     * @type {Array<string>}
     * @memberof HandlersDeletedNote
     */
    'filePath'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof HandlersDeletedNote
     */
    'id'?: string;
}
/**
 * 
 * @export
 * @interface HandlersHttpErrorAny
 */
export interface HandlersHttpErrorAny {
    /**
     * 
     * @type {object}
     * @memberof HandlersHttpErrorAny
     */
    'data'?: object;
    /**
     * 
     * @type {string}
     * @memberof HandlersHttpErrorAny
     */
    'message'?: string;
}
/**
 * 
 * @export
 * @interface HandlersHttpResponseAnyAny
 */
export interface HandlersHttpResponseAnyAny {
    /**
     * 
     * @type {object}
     * @memberof HandlersHttpResponseAnyAny
     */
    'data'?: object;
    /**
     * 
     * @type {object}
     * @memberof HandlersHttpResponseAnyAny
     */
    'meta'?: object;
}
/**
 * 
 * @export
 * @interface HandlersHttpResponseArrayModelsAPITokenAny
 */
export interface HandlersHttpResponseArrayModelsAPITokenAny {
    /**
     * 
     * @type {Array<ModelsAPIToken>}
     * @memberof HandlersHttpResponseArrayModelsAPITokenAny
     */
    'data'?: Array<ModelsAPIToken>;
    /**
     * 
     * @type {object}
     * @memberof HandlersHttpResponseArrayModelsAPITokenAny
     */
    'meta'?: object;
}
/**
 * 
 * @export
 * @interface HandlersHttpResponseArrayModelsPublicNoteModelsPagination
 */
export interface HandlersHttpResponseArrayModelsPublicNoteModelsPagination {
    /**
     * 
     * @type {Array<ModelsPublicNote>}
     * @memberof HandlersHttpResponseArrayModelsPublicNoteModelsPagination
     */
    'data'?: Array<ModelsPublicNote>;
    /**
     * 
     * @type {ModelsPagination}
     * @memberof HandlersHttpResponseArrayModelsPublicNoteModelsPagination
     */
    'meta'?: ModelsPagination;
}
/**
 * 
 * @export
 * @interface HandlersHttpResponseArrayStringAny
 */
export interface HandlersHttpResponseArrayStringAny {
    /**
     * 
     * @type {Array<string>}
     * @memberof HandlersHttpResponseArrayStringAny
     */
    'data'?: Array<string>;
    /**
     * 
     * @type {object}
     * @memberof HandlersHttpResponseArrayStringAny
     */
    'meta'?: object;
}
/**
 * 
 * @export
 * @interface HandlersHttpResponseHandlersOAuthRedirectDataAny
 */
export interface HandlersHttpResponseHandlersOAuthRedirectDataAny {
    /**
     * 
     * @type {HandlersOAuthRedirectData}
     * @memberof HandlersHttpResponseHandlersOAuthRedirectDataAny
     */
    'data'?: HandlersOAuthRedirectData;
    /**
     * 
     * @type {object}
     * @memberof HandlersHttpResponseHandlersOAuthRedirectDataAny
     */
    'meta'?: object;
}
/**
 * 
 * @export
 * @interface HandlersHttpResponseHandlersSyncNotesResponseAny
 */
export interface HandlersHttpResponseHandlersSyncNotesResponseAny {
    /**
     * 
     * @type {HandlersSyncNotesResponse}
     * @memberof HandlersHttpResponseHandlersSyncNotesResponseAny
     */
    'data'?: HandlersSyncNotesResponse;
    /**
     * 
     * @type {object}
     * @memberof HandlersHttpResponseHandlersSyncNotesResponseAny
     */
    'meta'?: object;
}
/**
 * 
 * @export
 * @interface HandlersHttpResponseModelsAPITokenAny
 */
export interface HandlersHttpResponseModelsAPITokenAny {
    /**
     * 
     * @type {ModelsAPIToken}
     * @memberof HandlersHttpResponseModelsAPITokenAny
     */
    'data'?: ModelsAPIToken;
    /**
     * 
     * @type {object}
     * @memberof HandlersHttpResponseModelsAPITokenAny
     */
    'meta'?: object;
}
/**
 * 
 * @export
 * @interface HandlersHttpResponseModelsPublicNoteAny
 */
export interface HandlersHttpResponseModelsPublicNoteAny {
    /**
     * 
     * @type {ModelsPublicNote}
     * @memberof HandlersHttpResponseModelsPublicNoteAny
     */
    'data'?: ModelsPublicNote;
    /**
     * 
     * @type {object}
     * @memberof HandlersHttpResponseModelsPublicNoteAny
     */
    'meta'?: object;
}
/**
 * 
 * @export
 * @interface HandlersHttpResponseModelsUserPersonalInfoAny
 */
export interface HandlersHttpResponseModelsUserPersonalInfoAny {
    /**
     * 
     * @type {ModelsUserPersonalInfo}
     * @memberof HandlersHttpResponseModelsUserPersonalInfoAny
     */
    'data'?: ModelsUserPersonalInfo;
    /**
     * 
     * @type {object}
     * @memberof HandlersHttpResponseModelsUserPersonalInfoAny
     */
    'meta'?: object;
}
/**
 * 
 * @export
 * @interface HandlersOAuthRedirectData
 */
export interface HandlersOAuthRedirectData {
    /**
     * 
     * @type {string}
     * @memberof HandlersOAuthRedirectData
     */
    'redirectUrl'?: string;
}
/**
 * 
 * @export
 * @interface HandlersSubscribeBody
 */
export interface HandlersSubscribeBody {
    /**
     * 
     * @type {string}
     * @memberof HandlersSubscribeBody
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof HandlersSubscribeBody
     */
    'token'?: string;
}
/**
 * 
 * @export
 * @interface HandlersSyncNotesRequest
 */
export interface HandlersSyncNotesRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof HandlersSyncNotesRequest
     */
    'deletedNotesIds'?: Array<string>;
    /**
     * 
     * @type {Array<HandlersCreatingNote>}
     * @memberof HandlersSyncNotesRequest
     */
    'notes'?: Array<HandlersCreatingNote>;
    /**
     * 
     * @type {string}
     * @memberof HandlersSyncNotesRequest
     */
    'timestamp'?: string;
}
/**
 * 
 * @export
 * @interface HandlersSyncNotesResponse
 */
export interface HandlersSyncNotesResponse {
    /**
     * 
     * @type {Array<HandlersDeletedNote>}
     * @memberof HandlersSyncNotesResponse
     */
    'deletedNotes'?: Array<HandlersDeletedNote>;
    /**
     * 
     * @type {Array<ModelsPublicNote>}
     * @memberof HandlersSyncNotesResponse
     */
    'notes'?: Array<ModelsPublicNote>;
}
/**
 * 
 * @export
 * @interface ModelsAPIToken
 */
export interface ModelsAPIToken {
    /**
     * 
     * @type {string}
     * @memberof ModelsAPIToken
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsAPIToken
     */
    'permission'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsAPIToken
     */
    'token'?: string;
}
/**
 * 
 * @export
 * @enum {string}
 */

export const ModelsCategory = {
    CategoryArticle: 'article',
    CategoryBook: 'book',
    CategorySchedule: 'schedule'
} as const;

export type ModelsCategory = typeof ModelsCategory[keyof typeof ModelsCategory];


/**
 * 
 * @export
 * @interface ModelsNoteHeading
 */
export interface ModelsNoteHeading {
    /**
     * 
     * @type {number}
     * @memberof ModelsNoteHeading
     */
    'level'?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsNoteHeading
     */
    'text'?: string;
}
/**
 * 
 * @export
 * @interface ModelsNoteLink
 */
export interface ModelsNoteLink {
    /**
     * 
     * @type {string}
     * @memberof ModelsNoteLink
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsNoteLink
     */
    'url'?: string;
}
/**
 * 
 * @export
 * @interface ModelsNoteMeta
 */
export interface ModelsNoteMeta {
    /**
     * 
     * @type {ModelsCategory}
     * @memberof ModelsNoteMeta
     */
    'category'?: ModelsCategory;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ModelsNoteMeta
     */
    'connectedNotes'?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof ModelsNoteMeta
     */
    'description'?: string;
    /**
     * 
     * @type {Array<ModelsNoteLink>}
     * @memberof ModelsNoteMeta
     */
    'externalLinks'?: Array<ModelsNoteLink>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ModelsNoteMeta
     */
    'fileTags'?: Array<string>;
    /**
     * 
     * @type {Array<ModelsNoteHeading>}
     * @memberof ModelsNoteMeta
     */
    'headings'?: Array<ModelsNoteHeading>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ModelsNoteMeta
     */
    'images'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ModelsNoteMeta
     */
    'previewImg'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsNoteMeta
     */
    'published'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelsNoteMeta
     */
    'startup'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsNoteMeta
     */
    'title'?: string;
}


/**
 * 
 * @export
 * @interface ModelsOrgNoteClientUpdateInfo
 */
export interface ModelsOrgNoteClientUpdateInfo {
    /**
     * 
     * @type {string}
     * @memberof ModelsOrgNoteClientUpdateInfo
     */
    'changeLog'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsOrgNoteClientUpdateInfo
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsOrgNoteClientUpdateInfo
     */
    'version'?: string;
}
/**
 * 
 * @export
 * @interface ModelsPagination
 */
export interface ModelsPagination {
    /**
     * 
     * @type {number}
     * @memberof ModelsPagination
     */
    'limit'?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsPagination
     */
    'offset'?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsPagination
     */
    'total'?: number;
}
/**
 * 
 * @export
 * @interface ModelsPublicNote
 */
export interface ModelsPublicNote {
    /**
     * 
     * @type {ModelsPublicUser}
     * @memberof ModelsPublicNote
     */
    'author'?: ModelsPublicUser;
    /**
     * 
     * @type {string}
     * @memberof ModelsPublicNote
     */
    'content': string;
    /**
     * 
     * @type {string}
     * @memberof ModelsPublicNote
     */
    'createdAt'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsPublicNote
     */
    'encrypted'?: boolean;
    /**
     * Encrypted note content
     * @type {string}
     * @memberof ModelsPublicNote
     */
    'encryptionType'?: ModelsPublicNoteEncryptionTypeEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof ModelsPublicNote
     */
    'filePath'?: Array<string>;
    /**
     * It\'s externalID from original note
     * @type {string}
     * @memberof ModelsPublicNote
     */
    'id'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsPublicNote
     */
    'isMy'?: boolean;
    /**
     * 
     * @type {ModelsNoteMeta}
     * @memberof ModelsPublicNote
     */
    'meta': ModelsNoteMeta;
    /**
     * 
     * @type {number}
     * @memberof ModelsPublicNote
     */
    'size'?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsPublicNote
     */
    'touchedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsPublicNote
     */
    'updatedAt'?: string;
}

export const ModelsPublicNoteEncryptionTypeEnum = {
    GpgKeys: 'gpgKeys',
    GpgPassword: 'gpgPassword',
    Disabled: 'disabled'
} as const;

export type ModelsPublicNoteEncryptionTypeEnum = typeof ModelsPublicNoteEncryptionTypeEnum[keyof typeof ModelsPublicNoteEncryptionTypeEnum];

/**
 * 
 * @export
 * @interface ModelsPublicUser
 */
export interface ModelsPublicUser {
    /**
     * 
     * @type {string}
     * @memberof ModelsPublicUser
     */
    'avatarUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsPublicUser
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsPublicUser
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsPublicUser
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsPublicUser
     */
    'nickName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsPublicUser
     */
    'profileUrl'?: string;
}
/**
 * 
 * @export
 * @interface ModelsUserPersonalInfo
 */
export interface ModelsUserPersonalInfo {
    /**
     * 
     * @type {string}
     * @memberof ModelsUserPersonalInfo
     */
    'active'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUserPersonalInfo
     */
    'avatarUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUserPersonalInfo
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUserPersonalInfo
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUserPersonalInfo
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUserPersonalInfo
     */
    'nickName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUserPersonalInfo
     */
    'profileUrl'?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsUserPersonalInfo
     */
    'spaceLimit'?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsUserPersonalInfo
     */
    'usedSpace'?: number;
}

/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Delete user account
         * @summary Delete user account
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authAccountDelete: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/account`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Return all available API tokens
         * @summary Get API tokens
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authApiTokensGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/api-tokens`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLogoutGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Callback for OAuth
         * @param {string} provider provider
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authProviderCallbackGet: async (provider: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'provider' is not null or undefined
            assertParamExists('authProviderCallbackGet', 'provider', provider)
            const localVarPath = `/auth/{provider}/callback`
                .replace(`{${"provider"}}`, encodeURIComponent(String(provider)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Entrypoint for login
         * @summary OAuth Login
         * @param {string} provider provider
         * @param {string} [state] OAuth state
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authProviderLoginGet: async (provider: string, state?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'provider' is not null or undefined
            assertParamExists('authProviderLoginGet', 'provider', provider)
            const localVarPath = `/auth/{provider}/login`
                .replace(`{${"provider"}}`, encodeURIComponent(String(provider)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (state !== undefined) {
                localVarQueryParameter['state'] = state;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Subscribe for backend features, like sync notes
         * @summary Subscribe
         * @param {HandlersSubscribeBody} data token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authSubscribePost: async (data: HandlersSubscribeBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'data' is not null or undefined
            assertParamExists('authSubscribePost', 'data', data)
            const localVarPath = `/auth/subscribe`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(data, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create API token
         * @summary Create API token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authTokenPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/token`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete API token
         * @summary Delete API token
         * @param {string} tokenId token id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authTokenTokenIdDelete: async (tokenId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tokenId' is not null or undefined
            assertParamExists('authTokenTokenIdDelete', 'tokenId', tokenId)
            const localVarPath = `/auth/token/{tokenId}`
                .replace(`{${"tokenId"}}`, encodeURIComponent(String(tokenId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Return found user by provided token
         * @summary Verify user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authVerifyGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/verify`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * Delete user account
         * @summary Delete user account
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authAccountDelete(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authAccountDelete(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authAccountDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Return all available API tokens
         * @summary Get API tokens
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authApiTokensGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HandlersHttpResponseArrayModelsAPITokenAny>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authApiTokensGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authApiTokensGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authLogoutGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authLogoutGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authLogoutGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Callback for OAuth
         * @param {string} provider provider
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authProviderCallbackGet(provider: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authProviderCallbackGet(provider, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authProviderCallbackGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Entrypoint for login
         * @summary OAuth Login
         * @param {string} provider provider
         * @param {string} [state] OAuth state
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authProviderLoginGet(provider: string, state?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HandlersHttpResponseHandlersOAuthRedirectDataAny>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authProviderLoginGet(provider, state, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authProviderLoginGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Subscribe for backend features, like sync notes
         * @summary Subscribe
         * @param {HandlersSubscribeBody} data token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authSubscribePost(data: HandlersSubscribeBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authSubscribePost(data, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authSubscribePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Create API token
         * @summary Create API token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authTokenPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HandlersHttpResponseModelsAPITokenAny>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authTokenPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authTokenPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Delete API token
         * @summary Delete API token
         * @param {string} tokenId token id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authTokenTokenIdDelete(tokenId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authTokenTokenIdDelete(tokenId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authTokenTokenIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Return found user by provided token
         * @summary Verify user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authVerifyGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HandlersHttpResponseModelsUserPersonalInfoAny>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authVerifyGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authVerifyGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * Delete user account
         * @summary Delete user account
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authAccountDelete(options?: any): AxiosPromise<object> {
            return localVarFp.authAccountDelete(options).then((request) => request(axios, basePath));
        },
        /**
         * Return all available API tokens
         * @summary Get API tokens
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authApiTokensGet(options?: any): AxiosPromise<HandlersHttpResponseArrayModelsAPITokenAny> {
            return localVarFp.authApiTokensGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLogoutGet(options?: any): AxiosPromise<object> {
            return localVarFp.authLogoutGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Callback for OAuth
         * @param {string} provider provider
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authProviderCallbackGet(provider: string, options?: any): AxiosPromise<object> {
            return localVarFp.authProviderCallbackGet(provider, options).then((request) => request(axios, basePath));
        },
        /**
         * Entrypoint for login
         * @summary OAuth Login
         * @param {string} provider provider
         * @param {string} [state] OAuth state
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authProviderLoginGet(provider: string, state?: string, options?: any): AxiosPromise<HandlersHttpResponseHandlersOAuthRedirectDataAny> {
            return localVarFp.authProviderLoginGet(provider, state, options).then((request) => request(axios, basePath));
        },
        /**
         * Subscribe for backend features, like sync notes
         * @summary Subscribe
         * @param {HandlersSubscribeBody} data token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authSubscribePost(data: HandlersSubscribeBody, options?: any): AxiosPromise<object> {
            return localVarFp.authSubscribePost(data, options).then((request) => request(axios, basePath));
        },
        /**
         * Create API token
         * @summary Create API token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authTokenPost(options?: any): AxiosPromise<HandlersHttpResponseModelsAPITokenAny> {
            return localVarFp.authTokenPost(options).then((request) => request(axios, basePath));
        },
        /**
         * Delete API token
         * @summary Delete API token
         * @param {string} tokenId token id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authTokenTokenIdDelete(tokenId: string, options?: any): AxiosPromise<object> {
            return localVarFp.authTokenTokenIdDelete(tokenId, options).then((request) => request(axios, basePath));
        },
        /**
         * Return found user by provided token
         * @summary Verify user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authVerifyGet(options?: any): AxiosPromise<HandlersHttpResponseModelsUserPersonalInfoAny> {
            return localVarFp.authVerifyGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI {
    /**
     * Delete user account
     * @summary Delete user account
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authAccountDelete(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authAccountDelete(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Return all available API tokens
     * @summary Get API tokens
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authApiTokensGet(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authApiTokensGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Logout
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authLogoutGet(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authLogoutGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Callback for OAuth
     * @param {string} provider provider
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authProviderCallbackGet(provider: string, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authProviderCallbackGet(provider, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Entrypoint for login
     * @summary OAuth Login
     * @param {string} provider provider
     * @param {string} [state] OAuth state
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authProviderLoginGet(provider: string, state?: string, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authProviderLoginGet(provider, state, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Subscribe for backend features, like sync notes
     * @summary Subscribe
     * @param {HandlersSubscribeBody} data token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authSubscribePost(data: HandlersSubscribeBody, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authSubscribePost(data, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create API token
     * @summary Create API token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authTokenPost(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authTokenPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete API token
     * @summary Delete API token
     * @param {string} tokenId token id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authTokenTokenIdDelete(tokenId: string, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authTokenTokenIdDelete(tokenId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Return found user by provided token
     * @summary Verify user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authVerifyGet(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authVerifyGet(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * FilesApi - axios parameter creator
 * @export
 */
export const FilesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Upload files.
         * @summary Upload files
         * @param {FilesUploadPostRequest} filesUploadPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        filesUploadPost: async (filesUploadPostRequest: FilesUploadPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'filesUploadPostRequest' is not null or undefined
            assertParamExists('filesUploadPost', 'filesUploadPostRequest', filesUploadPostRequest)
            const localVarPath = `/files/upload`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(filesUploadPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FilesApi - functional programming interface
 * @export
 */
export const FilesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FilesApiAxiosParamCreator(configuration)
    return {
        /**
         * Upload files.
         * @summary Upload files
         * @param {FilesUploadPostRequest} filesUploadPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async filesUploadPost(filesUploadPostRequest: FilesUploadPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.filesUploadPost(filesUploadPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FilesApi.filesUploadPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * FilesApi - factory interface
 * @export
 */
export const FilesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FilesApiFp(configuration)
    return {
        /**
         * Upload files.
         * @summary Upload files
         * @param {FilesUploadPostRequest} filesUploadPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        filesUploadPost(filesUploadPostRequest: FilesUploadPostRequest, options?: any): AxiosPromise<object> {
            return localVarFp.filesUploadPost(filesUploadPostRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FilesApi - object-oriented interface
 * @export
 * @class FilesApi
 * @extends {BaseAPI}
 */
export class FilesApi extends BaseAPI {
    /**
     * Upload files.
     * @summary Upload files
     * @param {FilesUploadPostRequest} filesUploadPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FilesApi
     */
    public filesUploadPost(filesUploadPostRequest: FilesUploadPostRequest, options?: RawAxiosRequestConfig) {
        return FilesApiFp(this.configuration).filesUploadPost(filesUploadPostRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * NotesApi - axios parameter creator
 * @export
 */
export const NotesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Force delete all user notes. This operation is irreversible
         * @summary Drop all user notes
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        allNotesDelete: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/all-notes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Bulk update or insert notes
         * @summary Upsert notes
         * @param {Array<HandlersCreatingNote>} notes List of crated notes
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notesBulkUpsertPut: async (notes: Array<HandlersCreatingNote>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'notes' is not null or undefined
            assertParamExists('notesBulkUpsertPut', 'notes', notes)
            const localVarPath = `/notes/bulk-upsert`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(notes, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Mark notes as deleted by provided list of ids
         * @summary Delete notes
         * @param {Array<string>} ids List of ids of deleted notes
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notesDelete: async (ids: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ids' is not null or undefined
            assertParamExists('notesDelete', 'ids', ids)
            const localVarPath = `/notes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(ids, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get all notes with optional filter
         * @summary Get notes
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {string} [userId] User id of which notes to load
         * @param {string} [searchText] 
         * @param {boolean} [my] Load all my own notes (user will be used from provided token)
         * @param {string} [from] 
         * @param {boolean} [includeDeleted] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notesGet: async (limit?: number, offset?: number, userId?: string, searchText?: string, my?: boolean, from?: string, includeDeleted?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/notes/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (userId !== undefined) {
                localVarQueryParameter['userId'] = userId;
            }

            if (searchText !== undefined) {
                localVarQueryParameter['searchText'] = searchText;
            }

            if (my !== undefined) {
                localVarQueryParameter['my'] = my;
            }

            if (from !== undefined) {
                localVarQueryParameter['from'] = from;
            }

            if (includeDeleted !== undefined) {
                localVarQueryParameter['includeDeleted'] = includeDeleted;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * get note by id
         * @summary Get note
         * @param {string} id Note ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notesIdGet: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('notesIdGet', 'id', id)
            const localVarPath = `/notes/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create note
         * @summary Create note
         * @param {HandlersCreatingNote} note Note model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notesPost: async (note: HandlersCreatingNote, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'note' is not null or undefined
            assertParamExists('notesPost', 'note', note)
            const localVarPath = `/notes/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(note, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Synchronize notes with specific timestamp
         * @summary Synchronize notes
         * @param {HandlersSyncNotesRequest} data Sync notes request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notesSyncPost: async (data: HandlersSyncNotesRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'data' is not null or undefined
            assertParamExists('notesSyncPost', 'data', data)
            const localVarPath = `/notes/sync`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(data, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * NotesApi - functional programming interface
 * @export
 */
export const NotesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = NotesApiAxiosParamCreator(configuration)
    return {
        /**
         * Force delete all user notes. This operation is irreversible
         * @summary Drop all user notes
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async allNotesDelete(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.allNotesDelete(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotesApi.allNotesDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Bulk update or insert notes
         * @summary Upsert notes
         * @param {Array<HandlersCreatingNote>} notes List of crated notes
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async notesBulkUpsertPut(notes: Array<HandlersCreatingNote>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.notesBulkUpsertPut(notes, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotesApi.notesBulkUpsertPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Mark notes as deleted by provided list of ids
         * @summary Delete notes
         * @param {Array<string>} ids List of ids of deleted notes
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async notesDelete(ids: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HandlersHttpResponseAnyAny>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.notesDelete(ids, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotesApi.notesDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get all notes with optional filter
         * @summary Get notes
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {string} [userId] User id of which notes to load
         * @param {string} [searchText] 
         * @param {boolean} [my] Load all my own notes (user will be used from provided token)
         * @param {string} [from] 
         * @param {boolean} [includeDeleted] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async notesGet(limit?: number, offset?: number, userId?: string, searchText?: string, my?: boolean, from?: string, includeDeleted?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HandlersHttpResponseArrayModelsPublicNoteModelsPagination>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.notesGet(limit, offset, userId, searchText, my, from, includeDeleted, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotesApi.notesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * get note by id
         * @summary Get note
         * @param {string} id Note ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async notesIdGet(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HandlersHttpResponseModelsPublicNoteAny>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.notesIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotesApi.notesIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Create note
         * @summary Create note
         * @param {HandlersCreatingNote} note Note model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async notesPost(note: HandlersCreatingNote, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.notesPost(note, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotesApi.notesPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Synchronize notes with specific timestamp
         * @summary Synchronize notes
         * @param {HandlersSyncNotesRequest} data Sync notes request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async notesSyncPost(data: HandlersSyncNotesRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HandlersHttpResponseHandlersSyncNotesResponseAny>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.notesSyncPost(data, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotesApi.notesSyncPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * NotesApi - factory interface
 * @export
 */
export const NotesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = NotesApiFp(configuration)
    return {
        /**
         * Force delete all user notes. This operation is irreversible
         * @summary Drop all user notes
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        allNotesDelete(options?: any): AxiosPromise<void> {
            return localVarFp.allNotesDelete(options).then((request) => request(axios, basePath));
        },
        /**
         * Bulk update or insert notes
         * @summary Upsert notes
         * @param {Array<HandlersCreatingNote>} notes List of crated notes
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notesBulkUpsertPut(notes: Array<HandlersCreatingNote>, options?: any): AxiosPromise<object> {
            return localVarFp.notesBulkUpsertPut(notes, options).then((request) => request(axios, basePath));
        },
        /**
         * Mark notes as deleted by provided list of ids
         * @summary Delete notes
         * @param {Array<string>} ids List of ids of deleted notes
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notesDelete(ids: Array<string>, options?: any): AxiosPromise<HandlersHttpResponseAnyAny> {
            return localVarFp.notesDelete(ids, options).then((request) => request(axios, basePath));
        },
        /**
         * Get all notes with optional filter
         * @summary Get notes
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {string} [userId] User id of which notes to load
         * @param {string} [searchText] 
         * @param {boolean} [my] Load all my own notes (user will be used from provided token)
         * @param {string} [from] 
         * @param {boolean} [includeDeleted] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notesGet(limit?: number, offset?: number, userId?: string, searchText?: string, my?: boolean, from?: string, includeDeleted?: boolean, options?: any): AxiosPromise<HandlersHttpResponseArrayModelsPublicNoteModelsPagination> {
            return localVarFp.notesGet(limit, offset, userId, searchText, my, from, includeDeleted, options).then((request) => request(axios, basePath));
        },
        /**
         * get note by id
         * @summary Get note
         * @param {string} id Note ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notesIdGet(id: string, options?: any): AxiosPromise<HandlersHttpResponseModelsPublicNoteAny> {
            return localVarFp.notesIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Create note
         * @summary Create note
         * @param {HandlersCreatingNote} note Note model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notesPost(note: HandlersCreatingNote, options?: any): AxiosPromise<object> {
            return localVarFp.notesPost(note, options).then((request) => request(axios, basePath));
        },
        /**
         * Synchronize notes with specific timestamp
         * @summary Synchronize notes
         * @param {HandlersSyncNotesRequest} data Sync notes request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notesSyncPost(data: HandlersSyncNotesRequest, options?: any): AxiosPromise<HandlersHttpResponseHandlersSyncNotesResponseAny> {
            return localVarFp.notesSyncPost(data, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * NotesApi - object-oriented interface
 * @export
 * @class NotesApi
 * @extends {BaseAPI}
 */
export class NotesApi extends BaseAPI {
    /**
     * Force delete all user notes. This operation is irreversible
     * @summary Drop all user notes
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotesApi
     */
    public allNotesDelete(options?: RawAxiosRequestConfig) {
        return NotesApiFp(this.configuration).allNotesDelete(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Bulk update or insert notes
     * @summary Upsert notes
     * @param {Array<HandlersCreatingNote>} notes List of crated notes
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotesApi
     */
    public notesBulkUpsertPut(notes: Array<HandlersCreatingNote>, options?: RawAxiosRequestConfig) {
        return NotesApiFp(this.configuration).notesBulkUpsertPut(notes, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Mark notes as deleted by provided list of ids
     * @summary Delete notes
     * @param {Array<string>} ids List of ids of deleted notes
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotesApi
     */
    public notesDelete(ids: Array<string>, options?: RawAxiosRequestConfig) {
        return NotesApiFp(this.configuration).notesDelete(ids, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get all notes with optional filter
     * @summary Get notes
     * @param {number} [limit] 
     * @param {number} [offset] 
     * @param {string} [userId] User id of which notes to load
     * @param {string} [searchText] 
     * @param {boolean} [my] Load all my own notes (user will be used from provided token)
     * @param {string} [from] 
     * @param {boolean} [includeDeleted] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotesApi
     */
    public notesGet(limit?: number, offset?: number, userId?: string, searchText?: string, my?: boolean, from?: string, includeDeleted?: boolean, options?: RawAxiosRequestConfig) {
        return NotesApiFp(this.configuration).notesGet(limit, offset, userId, searchText, my, from, includeDeleted, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * get note by id
     * @summary Get note
     * @param {string} id Note ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotesApi
     */
    public notesIdGet(id: string, options?: RawAxiosRequestConfig) {
        return NotesApiFp(this.configuration).notesIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create note
     * @summary Create note
     * @param {HandlersCreatingNote} note Note model
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotesApi
     */
    public notesPost(note: HandlersCreatingNote, options?: RawAxiosRequestConfig) {
        return NotesApiFp(this.configuration).notesPost(note, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Synchronize notes with specific timestamp
     * @summary Synchronize notes
     * @param {HandlersSyncNotesRequest} data Sync notes request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotesApi
     */
    public notesSyncPost(data: HandlersSyncNotesRequest, options?: RawAxiosRequestConfig) {
        return NotesApiFp(this.configuration).notesSyncPost(data, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * SystemInfoApi - axios parameter creator
 * @export
 */
export const SystemInfoApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary GetUpdatesFromVersion
         * @param {string} version provider
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        systemInfoClientUpdateVersionGet: async (version: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'version' is not null or undefined
            assertParamExists('systemInfoClientUpdateVersionGet', 'version', version)
            const localVarPath = `/system-info/client-update/{version}`
                .replace(`{${"version"}}`, encodeURIComponent(String(version)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SystemInfoApi - functional programming interface
 * @export
 */
export const SystemInfoApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SystemInfoApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary GetUpdatesFromVersion
         * @param {string} version provider
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async systemInfoClientUpdateVersionGet(version: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ModelsOrgNoteClientUpdateInfo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.systemInfoClientUpdateVersionGet(version, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SystemInfoApi.systemInfoClientUpdateVersionGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SystemInfoApi - factory interface
 * @export
 */
export const SystemInfoApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SystemInfoApiFp(configuration)
    return {
        /**
         * 
         * @summary GetUpdatesFromVersion
         * @param {string} version provider
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        systemInfoClientUpdateVersionGet(version: string, options?: any): AxiosPromise<ModelsOrgNoteClientUpdateInfo> {
            return localVarFp.systemInfoClientUpdateVersionGet(version, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SystemInfoApi - object-oriented interface
 * @export
 * @class SystemInfoApi
 * @extends {BaseAPI}
 */
export class SystemInfoApi extends BaseAPI {
    /**
     * 
     * @summary GetUpdatesFromVersion
     * @param {string} version provider
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SystemInfoApi
     */
    public systemInfoClientUpdateVersionGet(version: string, options?: RawAxiosRequestConfig) {
        return SystemInfoApiFp(this.configuration).systemInfoClientUpdateVersionGet(version, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * TagsApi - axios parameter creator
 * @export
 */
export const TagsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Return list of al registered tags
         * @summary Get tags
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tagsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/tags`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TagsApi - functional programming interface
 * @export
 */
export const TagsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TagsApiAxiosParamCreator(configuration)
    return {
        /**
         * Return list of al registered tags
         * @summary Get tags
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async tagsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HandlersHttpResponseArrayStringAny>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.tagsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TagsApi.tagsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TagsApi - factory interface
 * @export
 */
export const TagsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TagsApiFp(configuration)
    return {
        /**
         * Return list of al registered tags
         * @summary Get tags
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tagsGet(options?: any): AxiosPromise<HandlersHttpResponseArrayStringAny> {
            return localVarFp.tagsGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TagsApi - object-oriented interface
 * @export
 * @class TagsApi
 * @extends {BaseAPI}
 */
export class TagsApi extends BaseAPI {
    /**
     * Return list of al registered tags
     * @summary Get tags
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TagsApi
     */
    public tagsGet(options?: RawAxiosRequestConfig) {
        return TagsApiFp(this.configuration).tagsGet(options).then((request) => request(this.axios, this.basePath));
    }
}



