/* tslint:disable */
/* eslint-disable */
/**
 * Org Note API
 * List of methods for work with Org Note.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: artawower@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface FilesUploadPostRequest
 */
export interface FilesUploadPostRequest {
    /**
     * files
     * @type {Array<string>}
     * @memberof FilesUploadPostRequest
     */
    'files': Array<string>;
}
/**
 * 
 * @export
 * @interface HandlersHttpErrorAny
 */
export interface HandlersHttpErrorAny {
    /**
     * 
     * @type {object}
     * @memberof HandlersHttpErrorAny
     */
    'data'?: object;
    /**
     * 
     * @type {string}
     * @memberof HandlersHttpErrorAny
     */
    'message'?: string;
}
/**
 * 
 * @export
 * @interface HandlersHttpResponseArrayModelsAPITokenAny
 */
export interface HandlersHttpResponseArrayModelsAPITokenAny {
    /**
     * 
     * @type {Array<ModelsAPIToken>}
     * @memberof HandlersHttpResponseArrayModelsAPITokenAny
     */
    'data'?: Array<ModelsAPIToken>;
    /**
     * 
     * @type {object}
     * @memberof HandlersHttpResponseArrayModelsAPITokenAny
     */
    'meta'?: object;
}
/**
 * 
 * @export
 * @interface HandlersHttpResponseHandlersOAuthRedirectDataAny
 */
export interface HandlersHttpResponseHandlersOAuthRedirectDataAny {
    /**
     * 
     * @type {HandlersOAuthRedirectData}
     * @memberof HandlersHttpResponseHandlersOAuthRedirectDataAny
     */
    'data'?: HandlersOAuthRedirectData;
    /**
     * 
     * @type {object}
     * @memberof HandlersHttpResponseHandlersOAuthRedirectDataAny
     */
    'meta'?: object;
}
/**
 * 
 * @export
 * @interface HandlersHttpResponseModelsAPITokenAny
 */
export interface HandlersHttpResponseModelsAPITokenAny {
    /**
     * 
     * @type {ModelsAPIToken}
     * @memberof HandlersHttpResponseModelsAPITokenAny
     */
    'data'?: ModelsAPIToken;
    /**
     * 
     * @type {object}
     * @memberof HandlersHttpResponseModelsAPITokenAny
     */
    'meta'?: object;
}
/**
 * 
 * @export
 * @interface HandlersHttpResponseModelsUserPersonalInfoAny
 */
export interface HandlersHttpResponseModelsUserPersonalInfoAny {
    /**
     * 
     * @type {ModelsUserPersonalInfo}
     * @memberof HandlersHttpResponseModelsUserPersonalInfoAny
     */
    'data'?: ModelsUserPersonalInfo;
    /**
     * 
     * @type {object}
     * @memberof HandlersHttpResponseModelsUserPersonalInfoAny
     */
    'meta'?: object;
}
/**
 * 
 * @export
 * @interface HandlersOAuthRedirectData
 */
export interface HandlersOAuthRedirectData {
    /**
     * 
     * @type {string}
     * @memberof HandlersOAuthRedirectData
     */
    'redirectUrl'?: string;
}
/**
 * 
 * @export
 * @interface HandlersSubscribeBody
 */
export interface HandlersSubscribeBody {
    /**
     * 
     * @type {string}
     * @memberof HandlersSubscribeBody
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof HandlersSubscribeBody
     */
    'token'?: string;
}
/**
 * 
 * @export
 * @interface HandlersSystemInfo
 */
export interface HandlersSystemInfo {
    /**
     * 
     * @type {ModelsEnvironmentInfo}
     * @memberof HandlersSystemInfo
     */
    'environment'?: ModelsEnvironmentInfo;
    /**
     * 
     * @type {ModelsOrgNoteClientUpdateInfo}
     * @memberof HandlersSystemInfo
     */
    'update'?: ModelsOrgNoteClientUpdateInfo;
}
/**
 * 
 * @export
 * @interface ModelsAPIToken
 */
export interface ModelsAPIToken {
    /**
     * 
     * @type {string}
     * @memberof ModelsAPIToken
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsAPIToken
     */
    'permission'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsAPIToken
     */
    'token'?: string;
}
/**
 * 
 * @export
 * @interface ModelsEnvironmentInfo
 */
export interface ModelsEnvironmentInfo {
    /**
     * 
     * @type {boolean}
     * @memberof ModelsEnvironmentInfo
     */
    'selfHosted'?: boolean;
}
/**
 * 
 * @export
 * @interface ModelsOrgNoteClientUpdateInfo
 */
export interface ModelsOrgNoteClientUpdateInfo {
    /**
     * 
     * @type {string}
     * @memberof ModelsOrgNoteClientUpdateInfo
     */
    'changeLog'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsOrgNoteClientUpdateInfo
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsOrgNoteClientUpdateInfo
     */
    'version'?: string;
}
/**
 * 
 * @export
 * @interface ModelsUserPersonalInfo
 */
export interface ModelsUserPersonalInfo {
    /**
     * 
     * @type {string}
     * @memberof ModelsUserPersonalInfo
     */
    'active'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUserPersonalInfo
     */
    'avatarUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUserPersonalInfo
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUserPersonalInfo
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUserPersonalInfo
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUserPersonalInfo
     */
    'nickName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUserPersonalInfo
     */
    'profileUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUserPersonalInfo
     */
    'provider'?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsUserPersonalInfo
     */
    'spaceLimit'?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsUserPersonalInfo
     */
    'usedSpace'?: number;
}

/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Delete user account
         * @summary Delete user account
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authAccountDelete: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/account`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Return all available API tokens
         * @summary Get API tokens
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authApiTokensGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/api-tokens`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLogoutGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Callback for OAuth
         * @param {string} provider provider
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authProviderCallbackGet: async (provider: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'provider' is not null or undefined
            assertParamExists('authProviderCallbackGet', 'provider', provider)
            const localVarPath = `/auth/{provider}/callback`
                .replace(`{${"provider"}}`, encodeURIComponent(String(provider)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Entrypoint for login
         * @summary OAuth Login
         * @param {string} provider provider
         * @param {string} [state] OAuth state
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authProviderLoginGet: async (provider: string, state?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'provider' is not null or undefined
            assertParamExists('authProviderLoginGet', 'provider', provider)
            const localVarPath = `/auth/{provider}/login`
                .replace(`{${"provider"}}`, encodeURIComponent(String(provider)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (state !== undefined) {
                localVarQueryParameter['state'] = state;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Subscribe for backend features, like sync notes
         * @summary Subscribe
         * @param {HandlersSubscribeBody} data token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authSubscribePost: async (data: HandlersSubscribeBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'data' is not null or undefined
            assertParamExists('authSubscribePost', 'data', data)
            const localVarPath = `/auth/subscribe`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(data, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create API token
         * @summary Create API token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authTokenPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/token`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete API token
         * @summary Delete API token
         * @param {string} tokenId token id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authTokenTokenIdDelete: async (tokenId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tokenId' is not null or undefined
            assertParamExists('authTokenTokenIdDelete', 'tokenId', tokenId)
            const localVarPath = `/auth/token/{tokenId}`
                .replace(`{${"tokenId"}}`, encodeURIComponent(String(tokenId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Return found user by provided token
         * @summary Verify user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authVerifyGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/verify`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * Delete user account
         * @summary Delete user account
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authAccountDelete(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authAccountDelete(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authAccountDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Return all available API tokens
         * @summary Get API tokens
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authApiTokensGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HandlersHttpResponseArrayModelsAPITokenAny>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authApiTokensGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authApiTokensGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authLogoutGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authLogoutGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authLogoutGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Callback for OAuth
         * @param {string} provider provider
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authProviderCallbackGet(provider: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authProviderCallbackGet(provider, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authProviderCallbackGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Entrypoint for login
         * @summary OAuth Login
         * @param {string} provider provider
         * @param {string} [state] OAuth state
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authProviderLoginGet(provider: string, state?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HandlersHttpResponseHandlersOAuthRedirectDataAny>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authProviderLoginGet(provider, state, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authProviderLoginGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Subscribe for backend features, like sync notes
         * @summary Subscribe
         * @param {HandlersSubscribeBody} data token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authSubscribePost(data: HandlersSubscribeBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authSubscribePost(data, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authSubscribePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Create API token
         * @summary Create API token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authTokenPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HandlersHttpResponseModelsAPITokenAny>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authTokenPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authTokenPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Delete API token
         * @summary Delete API token
         * @param {string} tokenId token id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authTokenTokenIdDelete(tokenId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authTokenTokenIdDelete(tokenId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authTokenTokenIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Return found user by provided token
         * @summary Verify user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authVerifyGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HandlersHttpResponseModelsUserPersonalInfoAny>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authVerifyGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authVerifyGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * Delete user account
         * @summary Delete user account
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authAccountDelete(options?: any): AxiosPromise<object> {
            return localVarFp.authAccountDelete(options).then((request) => request(axios, basePath));
        },
        /**
         * Return all available API tokens
         * @summary Get API tokens
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authApiTokensGet(options?: any): AxiosPromise<HandlersHttpResponseArrayModelsAPITokenAny> {
            return localVarFp.authApiTokensGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLogoutGet(options?: any): AxiosPromise<object> {
            return localVarFp.authLogoutGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Callback for OAuth
         * @param {string} provider provider
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authProviderCallbackGet(provider: string, options?: any): AxiosPromise<object> {
            return localVarFp.authProviderCallbackGet(provider, options).then((request) => request(axios, basePath));
        },
        /**
         * Entrypoint for login
         * @summary OAuth Login
         * @param {string} provider provider
         * @param {string} [state] OAuth state
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authProviderLoginGet(provider: string, state?: string, options?: any): AxiosPromise<HandlersHttpResponseHandlersOAuthRedirectDataAny> {
            return localVarFp.authProviderLoginGet(provider, state, options).then((request) => request(axios, basePath));
        },
        /**
         * Subscribe for backend features, like sync notes
         * @summary Subscribe
         * @param {HandlersSubscribeBody} data token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authSubscribePost(data: HandlersSubscribeBody, options?: any): AxiosPromise<object> {
            return localVarFp.authSubscribePost(data, options).then((request) => request(axios, basePath));
        },
        /**
         * Create API token
         * @summary Create API token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authTokenPost(options?: any): AxiosPromise<HandlersHttpResponseModelsAPITokenAny> {
            return localVarFp.authTokenPost(options).then((request) => request(axios, basePath));
        },
        /**
         * Delete API token
         * @summary Delete API token
         * @param {string} tokenId token id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authTokenTokenIdDelete(tokenId: string, options?: any): AxiosPromise<object> {
            return localVarFp.authTokenTokenIdDelete(tokenId, options).then((request) => request(axios, basePath));
        },
        /**
         * Return found user by provided token
         * @summary Verify user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authVerifyGet(options?: any): AxiosPromise<HandlersHttpResponseModelsUserPersonalInfoAny> {
            return localVarFp.authVerifyGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI {
    /**
     * Delete user account
     * @summary Delete user account
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authAccountDelete(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authAccountDelete(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Return all available API tokens
     * @summary Get API tokens
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authApiTokensGet(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authApiTokensGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Logout
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authLogoutGet(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authLogoutGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Callback for OAuth
     * @param {string} provider provider
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authProviderCallbackGet(provider: string, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authProviderCallbackGet(provider, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Entrypoint for login
     * @summary OAuth Login
     * @param {string} provider provider
     * @param {string} [state] OAuth state
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authProviderLoginGet(provider: string, state?: string, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authProviderLoginGet(provider, state, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Subscribe for backend features, like sync notes
     * @summary Subscribe
     * @param {HandlersSubscribeBody} data token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authSubscribePost(data: HandlersSubscribeBody, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authSubscribePost(data, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create API token
     * @summary Create API token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authTokenPost(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authTokenPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete API token
     * @summary Delete API token
     * @param {string} tokenId token id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authTokenTokenIdDelete(tokenId: string, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authTokenTokenIdDelete(tokenId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Return found user by provided token
     * @summary Verify user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authVerifyGet(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authVerifyGet(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * FilesApi - axios parameter creator
 * @export
 */
export const FilesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Upload files.
         * @summary Upload files
         * @param {FilesUploadPostRequest} filesUploadPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        filesUploadPost: async (filesUploadPostRequest: FilesUploadPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'filesUploadPostRequest' is not null or undefined
            assertParamExists('filesUploadPost', 'filesUploadPostRequest', filesUploadPostRequest)
            const localVarPath = `/files/upload`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(filesUploadPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FilesApi - functional programming interface
 * @export
 */
export const FilesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FilesApiAxiosParamCreator(configuration)
    return {
        /**
         * Upload files.
         * @summary Upload files
         * @param {FilesUploadPostRequest} filesUploadPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async filesUploadPost(filesUploadPostRequest: FilesUploadPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.filesUploadPost(filesUploadPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FilesApi.filesUploadPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * FilesApi - factory interface
 * @export
 */
export const FilesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FilesApiFp(configuration)
    return {
        /**
         * Upload files.
         * @summary Upload files
         * @param {FilesUploadPostRequest} filesUploadPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        filesUploadPost(filesUploadPostRequest: FilesUploadPostRequest, options?: any): AxiosPromise<object> {
            return localVarFp.filesUploadPost(filesUploadPostRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FilesApi - object-oriented interface
 * @export
 * @class FilesApi
 * @extends {BaseAPI}
 */
export class FilesApi extends BaseAPI {
    /**
     * Upload files.
     * @summary Upload files
     * @param {FilesUploadPostRequest} filesUploadPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FilesApi
     */
    public filesUploadPost(filesUploadPostRequest: FilesUploadPostRequest, options?: RawAxiosRequestConfig) {
        return FilesApiFp(this.configuration).filesUploadPost(filesUploadPostRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * SystemInfoApi - axios parameter creator
 * @export
 */
export const SystemInfoApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary GetUpdatesFromVersion
         * @param {string} version provider
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        systemInfoClientUpdateVersionGet: async (version: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'version' is not null or undefined
            assertParamExists('systemInfoClientUpdateVersionGet', 'version', version)
            const localVarPath = `/system-info/client-update/{version}`
                .replace(`{${"version"}}`, encodeURIComponent(String(version)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get system info
         * @summary GetSystemInfo
         * @param {string} version provider
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        systemInfoVersionGet: async (version: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'version' is not null or undefined
            assertParamExists('systemInfoVersionGet', 'version', version)
            const localVarPath = `/system-info/{version}`
                .replace(`{${"version"}}`, encodeURIComponent(String(version)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SystemInfoApi - functional programming interface
 * @export
 */
export const SystemInfoApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SystemInfoApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary GetUpdatesFromVersion
         * @param {string} version provider
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async systemInfoClientUpdateVersionGet(version: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ModelsOrgNoteClientUpdateInfo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.systemInfoClientUpdateVersionGet(version, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SystemInfoApi.systemInfoClientUpdateVersionGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get system info
         * @summary GetSystemInfo
         * @param {string} version provider
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async systemInfoVersionGet(version: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HandlersSystemInfo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.systemInfoVersionGet(version, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SystemInfoApi.systemInfoVersionGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SystemInfoApi - factory interface
 * @export
 */
export const SystemInfoApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SystemInfoApiFp(configuration)
    return {
        /**
         * 
         * @summary GetUpdatesFromVersion
         * @param {string} version provider
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        systemInfoClientUpdateVersionGet(version: string, options?: any): AxiosPromise<ModelsOrgNoteClientUpdateInfo> {
            return localVarFp.systemInfoClientUpdateVersionGet(version, options).then((request) => request(axios, basePath));
        },
        /**
         * Get system info
         * @summary GetSystemInfo
         * @param {string} version provider
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        systemInfoVersionGet(version: string, options?: any): AxiosPromise<HandlersSystemInfo> {
            return localVarFp.systemInfoVersionGet(version, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SystemInfoApi - object-oriented interface
 * @export
 * @class SystemInfoApi
 * @extends {BaseAPI}
 */
export class SystemInfoApi extends BaseAPI {
    /**
     * 
     * @summary GetUpdatesFromVersion
     * @param {string} version provider
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SystemInfoApi
     */
    public systemInfoClientUpdateVersionGet(version: string, options?: RawAxiosRequestConfig) {
        return SystemInfoApiFp(this.configuration).systemInfoClientUpdateVersionGet(version, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get system info
     * @summary GetSystemInfo
     * @param {string} version provider
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SystemInfoApi
     */
    public systemInfoVersionGet(version: string, options?: RawAxiosRequestConfig) {
        return SystemInfoApiFp(this.configuration).systemInfoVersionGet(version, options).then((request) => request(this.axios, this.basePath));
    }
}



